controller_list:
  - name: arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - ma2010_joint_1_s
      - ma2010_joint_2_l
      - ma2010_joint_3_u
      - ma2010_joint_4_r
      - ma2010_joint_5_b
      - ma2010_joint_6_t
  - name: positioner_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - d500_joint_1
      - d500_joint_2
