controller_list:
  - name: controller_sim/arm
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [ma2010_joint_1_s, ma2010_joint_2_l, ma2010_joint_3_u, ma2010_joint_4_r, ma2010_joint_5_b, ma2010_joint_6_t]
  - name: controller_sim/positioner
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [d500_joint_1, d500_joint_2]
